## Flox Environment Manifest -----------------------------------------
##
##   _Everything_ you need to know about the _manifest_ is here:
##
##               https://flox.dev/docs/concepts/manifest
##
## -------------------------------------------------------------------
# Flox manifest version managed by Flox CLI
version = 1


## Install Packages --------------------------------------------------
##  $ flox install gum  <- puts a package in [install] section below
##  $ flox search gum   <- search for a package
##  $ flox show gum     <- show all versions of a package
## -------------------------------------------------------------------
[install]
# Shell
zsh.pkg-path = "zsh"
# TODO: Need to manage the config too
starship.pkg-path = "starship"
zsh-syntax-highlighting.pkg-path = "zsh-syntax-highlighting"
zsh-autosuggestions.pkg-path = "zsh-autosuggestions"

# Docker
docker.pkg-path = "docker"
docker-compose.pkg-path = "docker-compose"

# Misc
tree.pkg-path = "tree"
shellcheck.pkg-path = "shellcheck"
gnumake.pkg-path = "gnumake"
pre-commit.pkg-path = "pre-commit"
direnv.pkg-path = "direnv"
jq.pkg-path = "jq"
yq-go.pkg-path = "yq-go"
openssl.pkg-path = "openssl"
jujutsu.pkg-path = "jujutsu"
asciinema.pkg-path = "asciinema"
asciinema-agg.pkg-path = "asciinema-agg"
ripgrep.pkg-path = "ripgrep"
fzf.pkg-path = "fzf"

## Environment Variables ---------------------------------------------
##  ... available for use in the activated environment
##      as well as [hook], [profile] scripts and [services] below.
## -------------------------------------------------------------------
[vars]
# INTRO_MESSAGE = "It's gettin' Flox in here"


## Activation Hook ---------------------------------------------------
##  ... run by _bash_ shell when you run 'flox activate'.
## -------------------------------------------------------------------
[hook]
# on-activate = '''
#   # -> Set variables, create files and directories
#   # -> Perform initialization steps, e.g. create a python venv
#   # -> Useful environment variables:
#   #      - FLOX_ENV_PROJECT=/home/user/example
#   #      - FLOX_ENV=/home/user/example/.flox/run
#   #      - FLOX_ENV_CACHE=/home/user/example/.flox/cache
# '''


## Profile script ----------------------------------------------------
## ... sourced by _your shell_ when you run 'flox activate'.
## -------------------------------------------------------------------
[profile]
common = '''
eval "$(starship init zsh)"
source $FLOX_ENV/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $FLOX_ENV/share/zsh-autosuggestions/zsh-autosuggestions.zsh
'''
## Shell specific profiles go here:
# bash = ...
# zsh  = ...
# fish = ...


## Services ----------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
## -------------------------------------------------------------------
[services]
# myservice.command = "python3 -m http.server"


## Other Environment Options -----------------------------------------
[options]
# Systems that environment is compatible with
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
# Uncomment to disable CUDA detection.
# cuda-detection = false
