## Flox Environment Manifest -----------------------------------------
##
##   _Everything_ you need to know about the _manifest_ is here:
##
##   https://flox.dev/docs/reference/command-reference/manifest.toml/
##
## -------------------------------------------------------------------
# Flox manifest version managed by Flox CLI
schema-version = "1.10.0"


## Install Packages --------------------------------------------------
##  $ flox install gum  <- puts a package in [install] section below
##  $ flox search gum   <- search for a package
##  $ flox show gum     <- show all versions of a package
## -------------------------------------------------------------------
[install]
jujutsu.pkg-path = "jujutsu"
jujutsu.pkg-group = "jujutsu"

starship.pkg-path = "starship"
marp-cli.pkg-path = "marp-cli"
asciinema.pkg-path = "asciinema"
asciinema-agg.pkg-path = "asciinema-agg"
ripgrep.pkg-path = "ripgrep"
direnv.pkg-path = "direnv"
gifsicle.pkg-path = "gifsicle"
claude-code.pkg-path = "claude-code"
go.pkg-path = "go"
gopls.pkg-path = "gopls"
pyright.pkg-path = "pyright"
gh.pkg-path = "gh"


## Environment Variables ---------------------------------------------
##  ... available for use in the activated environment
##      as well as [hook], [profile] scripts and [services] below.
## -------------------------------------------------------------------
[vars]
# INTRO_MESSAGE = "It's gettin' Flox in here"


## Activation Hook ---------------------------------------------------
##  ... run by _bash_ shell when you run 'flox activate'.
## -------------------------------------------------------------------
[hook]
on-activate = '''
case "$(uname)" in
  Darwin)
    GHOSTTY_DIR="$HOME/Library/Application Support/com.mitchellh.ghostty"
    VSCODE_DIR="$HOME/Library/Application Support/Code/User"
    ;;
  Linux)
    GHOSTTY_DIR="$HOME/.config/ghostty"
    VSCODE_DIR="$HOME/.config/Code/User"
    ;;
esac

export GIT_CONFIG_GLOBAL="$FLOX_ENV_PROJECT/config-files/.gitconfig"
export JJ_CONFIG="$FLOX_ENV_PROJECT/config-files/jj.config.toml"
export STARSHIP_CONFIG=$FLOX_ENV_PROJECT/config-files/starship.toml

mkdir -p "$GHOSTTY_DIR"
ln -sf "$FLOX_ENV_PROJECT/config-files/ghostty.ini" "$GHOSTTY_DIR/config"

mkdir -p "$VSCODE_DIR"
ln -sf "$FLOX_ENV_PROJECT/config-files/vscode-settings.json" "$VSCODE_DIR/settings.json"
'''


## Profile script ----------------------------------------------------
## ... sourced by _your shell_ when you run 'flox activate'.
## -------------------------------------------------------------------
[profile]
# common = '''
#   gum style \
#   --foreground 212 --border-foreground 212 --border double \
#   --align center --width 50 --margin "1 2" --padding "2 4" \
#     $INTRO_MESSAGE
# '''
## Shell-specific customizations such as setting aliases go here:
# bash = ...
# zsh  = ...
# fish = ...


## Services ---------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
## ------------------------------------------------------------------
[services]
# myservice.command = "python3 -m http.server"


## Include ----------------------------------------------------------
## ... environments to create a composed environment
## ------------------------------------------------------------------
[include]
# environments = [
#     { dir = "../common" }
# ]


## Build and publish your own packages ------------------------------
##  $ flox build
##  $ flox publish
## ------------------------------------------------------------------
[build]
# [build.myproject]
# description = "The coolest project ever"
# version = "0.0.1"
# command = """
#   mkdir -p $out/bin
#   cargo build --release
#   cp target/release/myproject $out/bin/myproject
# """


## Other Environment Options -----------------------------------------
[options]
# Systems that environment is compatible with
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
# Uncomment to disable CUDA detection.
# cuda-detection = false
