# Ghostty Config
keybind = global:cmd+grave_accent=toggle_quick_terminal
quick-terminal-animation-duration = 0
background-opacity = 0.80
background-blur-radius = 5

theme = Ayu
# font-family = "JetBrains Mono"
